# This is an example configuration, for production grade configuration see the Keycloak documentation.
# See https://www.keycloak.org/server/configuration
# See https://www.keycloak.org/server/all-config

image:
  tag: "26.0.2"

podSecurityContext: null



# SecurityContext for the Keycloak container
securityContext:
  runAsUser: 1007710000
  runAsNonRoot: true


command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--spi-events-listener-jboss-logging-success-level=info"
  - "--spi-events-listener-jboss-logging-error-level=warn"

extraEnv: |
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: {{ include "keycloak.fullname" . }}-admin-creds
        key: user
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ include "keycloak.fullname" . }}-admin-creds
        key: password
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:MaxRAMPercentage=50.0
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

route:
  # If `true`, an OpenShift Route is created
  enabled: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: false

dbchecker:
  enabled: false
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1007710010
    runAsGroup: 1007710010
    runAsNonRoot: true  

database:
  vendor: postgres
  hostname: keycloak-db-postgresql
  port: 5432
  username: dhansking
  password: test123pass
  database: keycloak

secrets:
  admin-creds:
    annotations:
      my-test-annotation: Test secret for {{ include "keycloak.fullname" . }}
    stringData:
      user: admin
      password: secret
